version: '3.8'

services:
  jupyterlab:
    build: .
    container_name: jupyterlab-kit
    ports:
      - "8888:8888"  # JupyterLab
    volumes:
      - .:/workspace
      - jupyter_data:/root/.jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/workspace
    working_dir: /workspace
    command: >
      bash -c "
        jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
      "
    restart: unless-stopped
    networks:
      - jupyterlab_network

  # 追加のサービス（オプション）
  # データベースやその他のサービスを追加したい場合はここに記述

volumes:
  jupyter_data:
    driver: local

networks:
  jupyterlab_network:
    driver: bridge