version: '3.8'

services:
  jupyterlab-dev:
    build: .
    container_name: jupyterlab-kit-dev
    ports:
      - "8888:8888"  # JupyterLab
    volumes:
      - .:/workspace
      - jupyter_data_dev:/root/.jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/workspace
    working_dir: /workspace
    command: >
      bash -c "
        echo '🌟✨ JupyterLab開発環境を起動中... ✨🌟' &&
        echo '💻 JupyterLab: http://localhost:8888' &&
        jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
      "
    restart: unless-stopped
    networks:
      - jupyterlab_dev_network

volumes:
  jupyter_data_dev:
    driver: local

networks:
  jupyterlab_dev_network:
    driver: bridge